preprocessing:
  split_ratio: 0.3
  input_trainset: ./data/train.csv
  input_testset: ./data/test.csv
  random_seed: 0
  classes:
    - 'Functionality_Test_Case'
    - 'User_Interface_Test_Case'
    - 'Performance_Test_Case'
    - 'Integration_Test_Case'
    - 'Usability_Test_Case'
    - 'Database_Test_Case'
    - 'Security_Test_Case'
    - 'User_Acceptance_Test_Case'
  input_text_column: Descrption
  input_id_column: Test_ID
  maxlen: 128
  skip_tokenization: false
  batch_size: 32
  input_convertor: count_vectorization
training:
  learning_rate: 1.0
  dropout_rate: 0.5
  batch_normalization: true
  optimizer: sgd
  epochs: 1
  gradient_cliping: true
  batch_size: 32
  embedding_dim: 128
  maxlen: 128
  predict_only: false
  output_path: ./output
  model_name: naivebayse
predict:
  output_path: ./data/result.csv
  enable_calibration: false
  calibrator_type: platt_scaling
  calibrators_output_path: ./output
  debug_validation: false
  classes:
    - 'Functionality_Test_Case'
    - 'User_Interface_Test_Case'
    - 'Performance_Test_Case'
    - 'Integration_Test_Case'
    - 'Usability_Test_Case'
    - 'Database_Test_Case'
    - 'Security_Test_Case'
    - 'User_Acceptance_Test_Case'
